### ISSUE TITLE
博客问题

### ISSUE THREAD

**Issue by bufsnake** [lei2rock/blog#45]
请问一下，你的博客顶部填充了10px是如何做到的

**Comment by lei2rock** [comment]
1. 在 [variables.styl](https://github.com/lei2rock/blog/blob/src/source/_data/variables.styl) 增加 `$site-top-margin` 变量
2. 在 [styles.styl](https://github.com/lei2rock/blog/blob/src/source/_data/styles.styl) 搜一下上面这个变量涉及的样式

**Comment by bufsnake** [comment]
我试试，感谢感谢




------------------ 原始邮件 ------------------
发件人: "Donglei Zhang"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 晚上6:48
收件人: "lei2rock/blog"<blog@noreply.github.com>; 
抄送: "张全"<1738961906@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lei2rock/blog] 博客问题 (#45)



 
在 variables.styl 增加 $site-top-margin 变量
 
在 styles.styl 搜一下上面这个变量涉及的样式
